"""initial_schema

Revision ID: e4672d817588
Revises: 
Create Date: 2025-11-16 22:58:02.813031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4672d817588'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Otel adı'),
    sa.Column('code', sa.String(length=50), nullable=True, comment='Otel kodu'),
    sa.Column('address', sa.Text(), nullable=True, comment='Adres'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Telefon'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='E-posta'),
    sa.Column('logo', sa.String(length=500), nullable=True, comment='Logo URL'),
    sa.Column('timezone', sa.String(length=50), server_default='Europe/Istanbul', nullable=False, comment='Otel timezone'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_code'), 'hotels', ['code'], unique=True)
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('hotel_id', sa.Integer(), nullable=False, comment='Otel ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Lokasyon adı'),
    sa.Column('description', sa.Text(), nullable=True, comment='Açıklama'),
    sa.Column('qr_code_data', sa.String(length=500), nullable=False, comment='QR kod verisi'),
    sa.Column('qr_code_image', sa.Text(), nullable=True, comment='QR kod görseli (base64)'),
    sa.Column('location_image', sa.Text(), nullable=True, comment='Lokasyon görseli'),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False, comment='Görüntüleme sırası'),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True, comment='Enlem'),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True, comment='Boylam'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Aktif mi?'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_display_order'), 'locations', ['display_order'], unique=False)
    op.create_index(op.f('ix_locations_hotel_id'), 'locations', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_is_active'), 'locations', ['is_active'], unique=False)
    op.create_index(op.f('ix_locations_qr_code_data'), 'locations', ['qr_code_data'], unique=True)
    op.create_table('system_users',
    sa.Column('hotel_id', sa.Integer(), nullable=False, comment='Otel ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Kullanıcı adı'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Şifre hash'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Kullanıcı rolü (admin/driver)'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Ad Soyad'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='E-posta'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Telefon'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Aktif mi?'),
    sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False, comment='Şifre değiştirmeli mi?'),
    sa.Column('fcm_token', sa.String(length=255), nullable=True, comment='FCM token'),
    sa.Column('fcm_token_date', sa.DateTime(), nullable=True, comment='FCM token kayıt tarihi'),
    sa.Column('notification_preferences', sa.Text(), nullable=True, comment='Bildirim tercihleri (JSON)'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='Son giriş zamanı'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_users_fcm_token'), 'system_users', ['fcm_token'], unique=False)
    op.create_index(op.f('ix_system_users_hotel_id'), 'system_users', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_system_users_id'), 'system_users', ['id'], unique=False)
    op.create_index(op.f('ix_system_users_is_active'), 'system_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_system_users_role'), 'system_users', ['role'], unique=False)
    op.create_index(op.f('ix_system_users_username'), 'system_users', ['username'], unique=True)
    op.create_table('audit_trail',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False, comment='Otel ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='İşlemi yapan kullanıcı ID'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='İşlem tipi (create/update/delete/login/logout)'),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='Etkilenen entity tipi (user/location/shuttle/request)'),
    sa.Column('entity_id', sa.Integer(), nullable=True, comment='Etkilenen entity ID'),
    sa.Column('old_values', sa.Text(), nullable=True, comment='Eski değerler (JSON)'),
    sa.Column('new_values', sa.Text(), nullable=True, comment='Yeni değerler (JSON)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP adresi'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User agent'),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False, comment='İşlem zamanı'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['system_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_trail_action'), 'audit_trail', ['action'], unique=False)
    op.create_index(op.f('ix_audit_trail_created_at'), 'audit_trail', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_trail_hotel_id'), 'audit_trail', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_audit_trail_id'), 'audit_trail', ['id'], unique=False)
    op.create_index(op.f('ix_audit_trail_user_id'), 'audit_trail', ['user_id'], unique=False)
    op.create_table('shuttles',
    sa.Column('hotel_id', sa.Integer(), nullable=False, comment='Otel ID'),
    sa.Column('current_location_id', sa.Integer(), nullable=True, comment='Mevcut lokasyon ID'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Shuttle kodu (örn: B01)'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='Model'),
    sa.Column('license_plate', sa.String(length=50), nullable=True, comment='Plaka'),
    sa.Column('icon', sa.String(length=10), nullable=True, comment='İkon emoji'),
    sa.Column('status', sa.String(length=20), server_default='available', nullable=False, comment='Shuttle durumu (available/busy/offline)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shuttles_code'), 'shuttles', ['code'], unique=True)
    op.create_index(op.f('ix_shuttles_current_location_id'), 'shuttles', ['current_location_id'], unique=False)
    op.create_index(op.f('ix_shuttles_hotel_id'), 'shuttles', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_shuttles_id'), 'shuttles', ['id'], unique=False)
    op.create_index(op.f('ix_shuttles_status'), 'shuttles', ['status'], unique=False)
    op.create_table('shuttle_drivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shuttle_id', sa.Integer(), nullable=False, comment='Shuttle ID'),
    sa.Column('driver_id', sa.Integer(), nullable=False, comment='Sürücü ID'),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False, comment='Birincil sürücü mü?'),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False, comment='Aktif mi?'),
    sa.Column('assigned_at', sa.DateTime(), server_default='now()', nullable=False, comment='Atanma zamanı'),
    sa.Column('last_active_at', sa.DateTime(), nullable=True, comment='Son aktif olma zamanı'),
    sa.ForeignKeyConstraint(['driver_id'], ['system_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shuttle_id'], ['shuttles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shuttle_id', 'driver_id', name='uq_shuttle_driver')
    )
    op.create_index(op.f('ix_shuttle_drivers_driver_id'), 'shuttle_drivers', ['driver_id'], unique=False)
    op.create_index(op.f('ix_shuttle_drivers_id'), 'shuttle_drivers', ['id'], unique=False)
    op.create_index(op.f('ix_shuttle_drivers_is_active'), 'shuttle_drivers', ['is_active'], unique=False)
    op.create_index(op.f('ix_shuttle_drivers_shuttle_id'), 'shuttle_drivers', ['shuttle_id'], unique=False)
    op.create_table('shuttle_requests',
    sa.Column('hotel_id', sa.Integer(), nullable=False, comment='Otel ID'),
    sa.Column('location_id', sa.Integer(), nullable=False, comment='Çağrı yapılan lokasyon ID'),
    sa.Column('completion_location_id', sa.Integer(), nullable=True, comment='Tamamlama lokasyonu ID'),
    sa.Column('shuttle_id', sa.Integer(), nullable=True, comment='Atanan shuttle ID'),
    sa.Column('accepted_by_id', sa.Integer(), nullable=True, comment='Kabul eden sürücü ID'),
    sa.Column('guest_name', sa.String(length=255), nullable=True, comment='Misafir adı'),
    sa.Column('room_number', sa.String(length=50), nullable=True, comment='Oda numarası'),
    sa.Column('has_room', sa.Boolean(), server_default='true', nullable=False, comment='Oda var mı?'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Telefon'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notlar'),
    sa.Column('guest_fcm_token', sa.String(length=500), nullable=True, comment='Misafir FCM token'),
    sa.Column('guest_fcm_token_expires_at', sa.DateTime(), nullable=True, comment='Token son kullanma tarihi'),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False, comment='Talep durumu'),
    sa.Column('cancelled_by', sa.String(length=50), nullable=True, comment='İptal eden (admin/driver/guest)'),
    sa.Column('requested_at', sa.DateTime(), server_default='now()', nullable=False, comment='Talep zamanı'),
    sa.Column('accepted_at', sa.DateTime(), nullable=True, comment='Kabul zamanı'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Tamamlanma zamanı'),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True, comment='İptal zamanı'),
    sa.Column('timeout_at', sa.DateTime(), nullable=True, comment='Timeout zamanı'),
    sa.Column('response_time', sa.Integer(), nullable=True, comment='Yanıt süresi (saniye)'),
    sa.Column('completion_time', sa.Integer(), nullable=True, comment='Tamamlanma süresi (saniye)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_id'], ['system_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completion_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shuttle_id'], ['shuttles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shuttle_requests_accepted_by_id'), 'shuttle_requests', ['accepted_by_id'], unique=False)
    op.create_index(op.f('ix_shuttle_requests_hotel_id'), 'shuttle_requests', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_shuttle_requests_id'), 'shuttle_requests', ['id'], unique=False)
    op.create_index(op.f('ix_shuttle_requests_location_id'), 'shuttle_requests', ['location_id'], unique=False)
    op.create_index(op.f('ix_shuttle_requests_requested_at'), 'shuttle_requests', ['requested_at'], unique=False)
    op.create_index(op.f('ix_shuttle_requests_room_number'), 'shuttle_requests', ['room_number'], unique=False)
    op.create_index(op.f('ix_shuttle_requests_shuttle_id'), 'shuttle_requests', ['shuttle_id'], unique=False)
    op.create_index(op.f('ix_shuttle_requests_status'), 'shuttle_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shuttle_requests_status'), table_name='shuttle_requests')
    op.drop_index(op.f('ix_shuttle_requests_shuttle_id'), table_name='shuttle_requests')
    op.drop_index(op.f('ix_shuttle_requests_room_number'), table_name='shuttle_requests')
    op.drop_index(op.f('ix_shuttle_requests_requested_at'), table_name='shuttle_requests')
    op.drop_index(op.f('ix_shuttle_requests_location_id'), table_name='shuttle_requests')
    op.drop_index(op.f('ix_shuttle_requests_id'), table_name='shuttle_requests')
    op.drop_index(op.f('ix_shuttle_requests_hotel_id'), table_name='shuttle_requests')
    op.drop_index(op.f('ix_shuttle_requests_accepted_by_id'), table_name='shuttle_requests')
    op.drop_table('shuttle_requests')
    op.drop_index(op.f('ix_shuttle_drivers_shuttle_id'), table_name='shuttle_drivers')
    op.drop_index(op.f('ix_shuttle_drivers_is_active'), table_name='shuttle_drivers')
    op.drop_index(op.f('ix_shuttle_drivers_id'), table_name='shuttle_drivers')
    op.drop_index(op.f('ix_shuttle_drivers_driver_id'), table_name='shuttle_drivers')
    op.drop_table('shuttle_drivers')
    op.drop_index(op.f('ix_shuttles_status'), table_name='shuttles')
    op.drop_index(op.f('ix_shuttles_id'), table_name='shuttles')
    op.drop_index(op.f('ix_shuttles_hotel_id'), table_name='shuttles')
    op.drop_index(op.f('ix_shuttles_current_location_id'), table_name='shuttles')
    op.drop_index(op.f('ix_shuttles_code'), table_name='shuttles')
    op.drop_table('shuttles')
    op.drop_index(op.f('ix_audit_trail_user_id'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_id'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_hotel_id'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_created_at'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_action'), table_name='audit_trail')
    op.drop_table('audit_trail')
    op.drop_index(op.f('ix_system_users_username'), table_name='system_users')
    op.drop_index(op.f('ix_system_users_role'), table_name='system_users')
    op.drop_index(op.f('ix_system_users_is_active'), table_name='system_users')
    op.drop_index(op.f('ix_system_users_id'), table_name='system_users')
    op.drop_index(op.f('ix_system_users_hotel_id'), table_name='system_users')
    op.drop_index(op.f('ix_system_users_fcm_token'), table_name='system_users')
    op.drop_table('system_users')
    op.drop_index(op.f('ix_locations_qr_code_data'), table_name='locations')
    op.drop_index(op.f('ix_locations_is_active'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_hotel_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_display_order'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_code'), table_name='hotels')
    op.drop_table('hotels')
    # ### end Alembic commands ###
