"""Add code field to Hotel model

Revision ID: 044c860e349e
Revises: f1bfa8e6cb66
Create Date: 2025-11-02 08:04:15.934548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044c860e349e'
down_revision = 'f1bfa8e6cb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
