"""Add code field to Hotel model

Revision ID: 044c860e349e
Revises: f1bfa8e6cb66
Create Date: 2025-11-02 08:04:15.934548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044c860e349e'
down_revision = 'f1bfa8e6cb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Check if hotels table exists and if code column already exists
    if 'hotels' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('hotels')]
        
        with op.batch_alter_table('hotels', schema=None) as batch_op:
            # Only add column if it doesn't exist
            if 'code' not in columns:
                batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=True))
                batch_op.create_unique_constraint(None, ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
