"""Add missing fields to BuggyRequest and Session models

Revision ID: 44056e92991c
Revises: 044c860e349e
Create Date: 2025-11-02 08:56:02.476112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44056e92991c'
down_revision = '044c860e349e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buggy_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_room', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('guest_device_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by', sa.String(length=50), nullable=True))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('last_activity', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('revoked_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sessions_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_is_active'))
        batch_op.drop_column('revoked_at')
        batch_op.drop_column('last_activity')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('buggy_requests', schema=None) as batch_op:
        batch_op.drop_column('cancelled_by')
        batch_op.drop_column('guest_device_id')
        batch_op.drop_column('has_room')

    # ### end Alembic commands ###
