"""Add guest_push_subscription to BuggyRequest

Revision ID: 74c532f38763
Revises: 002
Create Date: 2025-11-13 20:29:07.862605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74c532f38763'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buggy_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_push_subscription', sa.Text(), nullable=True))
        batch_op.alter_column('timeout_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Timestamp when request was marked as unanswered',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_requests_timeout_check'))

    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_users_fcm_token'), ['fcm_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_users_fcm_token'))

    with op.batch_alter_table('buggy_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_requests_timeout_check'), ['status', 'requested_at'], unique=False)
        batch_op.alter_column('timeout_at',
               existing_type=mysql.DATETIME(),
               comment='Timestamp when request was marked as unanswered',
               existing_nullable=True)
        batch_op.drop_column('guest_push_subscription')

    # ### end Alembic commands ###
