"""Add must_change_password to system_users

Revision ID: 779dc1a6fab7
Revises: c7dd1845ccb2
Create Date: 2025-11-03 01:37:16.584833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779dc1a6fab7'
down_revision = 'c7dd1845ccb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
