"""Add push_subscription field to SystemUser

Revision ID: a592b95be0e0
Revises: 44056e92991c
Create Date: 2025-11-02 08:58:32.681157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a592b95be0e0'
down_revision = '44056e92991c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_subscription', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.drop_column('push_subscription')

    # ### end Alembic commands ###
