"""Add icon field to Buggy model for visual identification

Revision ID: d8e9f0a1b2c3
Revises: c7dd1845ccb2
Create Date: 2025-11-03 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e9f0a1b2c3'
down_revision = '779dc1a6fab7'
branch_labels = None
depends_on = None


def upgrade():
    """Add icon column to buggies table"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buggies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    """Remove icon column from buggies table"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buggies', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
