"""Add current_location_id to Buggy model for location tracking

Revision ID: c7dd1845ccb2
Revises: a592b95be0e0
Create Date: 2025-11-02 09:52:08.504011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7dd1845ccb2'
down_revision = 'a592b95be0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buggies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_location_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_buggies_current_location_id'), ['current_location_id'], unique=False)
        batch_op.create_foreign_key(None, 'locations', ['current_location_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buggies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_buggies_current_location_id'))
        batch_op.drop_column('current_location_id')

    # ### end Alembic commands ###
