"""Initial migration with security updates

Revision ID: f1bfa8e6cb66
Revises: 
Create Date: 2025-11-02 07:42:52.190915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bfa8e6cb66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if locations table exists before altering
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    try:
        if 'locations' in inspector.get_table_names():
            # Only alter if table exists
            indexes = [idx['name'] for idx in inspector.get_indexes('locations')]
            
            with op.batch_alter_table('locations', schema=None) as batch_op:
                # Check if old index exists before dropping
                if 'idx_display_order' in indexes:
                    batch_op.drop_index('idx_display_order')
                
                # Create new index if it doesn't exist
                if 'ix_locations_display_order' not in indexes:
                    batch_op.create_index(batch_op.f('ix_locations_display_order'), ['display_order'], unique=False)
    except Exception as e:
        # Table doesn't exist yet, skip this migration
        print(f"Skipping locations index migration: {e}")
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if locations table exists before altering
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    try:
        if 'locations' in inspector.get_table_names():
            indexes = [idx['name'] for idx in inspector.get_indexes('locations')]
            
            with op.batch_alter_table('locations', schema=None) as batch_op:
                if 'ix_locations_display_order' in indexes:
                    batch_op.drop_index(batch_op.f('ix_locations_display_order'))
                if 'idx_display_order' not in indexes:
                    batch_op.create_index(batch_op.f('idx_display_order'), ['display_order'], unique=False)
    except Exception as e:
        print(f"Skipping locations index downgrade: {e}")
        pass
    # ### end Alembic commands ###
